stages:
  featurize:
    cmd: python3 src/featurize.py data/raw data/featurize
    deps:
    - data/raw
    - src/featurize.py
    params:
    - featurize.max_row_limit
    - featurize.window_size
    outs:
    - data/featurize
  train:
    cmd: python3 src/train.py data/featurize data/predictions
    deps:
    - data/featurize
    - src/model.py
    - src/train.py
    params:
    - featurize.window_size
    - train.batch_size
    - train.epochs
    - train.hidden_size
    outs:
    - data/predictions
